version: '3.2'

services:
  nginx:
    image: poldotz/pug-nginx:base
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - php-fpm
    ports:
      - 80:80

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/development/Dockerfile
    image: poldotz/pug-php-fpm:dev
    environment:
      XDEBUG_CONFIG: "remote_host=${XDEBUG_PORT:-docker.for.mac.host.internal} remote_port=${XDEBUG_PORT:-9000} idekey=${XDEBUG_IDEKEY:-PHPSTORM}"
      PHP_IDE_CONFIG: "serverName=localhost"
    depends_on:
      - memcached
    volumes:
      - "nfsmount::/var/www/html"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
