version: '3.2'

services:
  nginx:
    container_name: docker-project-nginx

  php-fpm:
    container_name: docker-project-php-fpm

  memcached:
    container_name: docker-project-memcached
    image: memcached:1.5.14-alpine

  yarn:
    container_name: docker-project-yarn
    image: node:8-alpine
    working_dir: /var/www/html
    environment:
      YARN_CACHE_FOLDER: /var/www/html/var/cache/yarn
    command: ['yarn', 'install']